server:
  port: 8181

app:
  bot:
    token: '8159929863:'
    name: 'sfasdfa'

spring:

  application:
    name: "telegabotat"

  datasource:
    url: 'sfasdf'
    username: 'asdfas'
    password: 'adfasf'
    driverClassName: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect