server:
  port: 8484

app:
  bot:
    token: '8159929863:AAFWMYpkCkjcfhAX2wGE7JJXbLlabRC0I3o'
    name: 'BotAutoTrading'

spring:
  application:
    name: "telegabotat"

  datasource:
    url: jdbc:postgresql://93.189.230.154:5432/telegabotbd
    username: telegabotbd
    password: telegabotbdadil
    driverClassName: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect