server:
  port: 8484

app:
  bot:
    token: ''
    name: ''

spring:

  profiles:
    active: prod

  application:
    name: "telegabotat"

  datasource:
    url: ''
    username: ''
    password: ''
    driverClassName: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect